resources:
- jenkins-slave.yaml
- secrets.yaml
- openeuler-pr-check-slaves.yaml
- web-sync-slaves.yaml
- license-check-slave.yaml
commonAnnotations:
  email: tommylikehu@gmail.com
  owner: tommylike
namespace: jenkins
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/mindspore/website_sync
  newTag: c5ef0c5cb98590ef2876098e664ff71e9b1fa3e4
