resources:
- analysis.yaml
- dm.yaml
- eureka.yaml
- gateway.yaml
- api-gateway.yaml
- ingress.yaml
- sca-namespace.yaml
- secrets.yaml
- web.yaml
- oauth-proxy.yaml
commonLabels:
  server: infrastructure-sca
commonAnnotations:
  email: xzq615@hotmail.com
  owner: xiaozhongqi
namespace: sca
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/sca-analysis
  newTag: e195219d626108b98df901846764b5a3a53a2095
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/sca-api-gateway
  newTag: e195219d626108b98df901846764b5a3a53a2095
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/sca-datamanager
  newTag: e195219d626108b98df901846764b5a3a53a2095
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/sca-web
  newTag: 50c79ec0a38205242cc35ee12e0fe37c44ac688f
